language: node_js
node_js:
  - "14"
services:
    - mysql
    -
dist:   xenial

env:
  - CXX=g++-4.8
mono:
  - latest
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
- mysql -e "create database IF NOT EXISTS test;" -uroot
- npm install -g grunt-cli


install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  #curl https://download.mono-project.com/repo/xamarin.gpg | sudo apt-key add -
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo apt-get update
  - echo "deb http://download.mono-project.com/repo/debian wheezy-apache24-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get install mono-devel
  - sudo apt-get install nunit-console
  - npm install edge
  - npm install
  - npm install edge-js
